import pc from 'picocolors';
import { join } from 'node:path';
import { readLockfile, type Lockfile } from '../core/cache/lockfile.js';
import { loadConfig } from '../core/config/loader.js';
import { printCompact } from '../ui/intro.js';
import { writeFile } from '../utils/fs.js';
import { getLanguageFlag } from '../utils/language.js';
import { VERSION } from '../utils/version.js';

export interface LocaleCoverage {
  locale: string;
  translated: number;
  total: number;
  percentage: number;
}

export interface CoverageReport {
  locales: LocaleCoverage[];
  totalKeys: number;
  overallPercentage: number;
}

export function computeCoverage(
  lockfile: Lockfile,
  targetLocales: string[],
): CoverageReport {
  const entries = lockfile.entries;

  let totalKeys = 0;
  const localeTranslated = new Map<string, number>();

  for (const locale of targetLocales) {
    localeTranslated.set(locale, 0);
  }

  for (const [_file, keys] of Object.entries(entries)) {
    for (const [_key, entry] of Object.entries(keys)) {
      totalKeys++;
      for (const locale of targetLocales) {
        if (entry.translations[locale]) {
          localeTranslated.set(locale, (localeTranslated.get(locale) ?? 0) + 1);
        }
      }
    }
  }

  const locales: LocaleCoverage[] = targetLocales.map((locale) => {
    const translated = localeTranslated.get(locale) ?? 0;
    const percentage = totalKeys > 0 ? Math.round((translated / totalKeys) * 100) : 0;
    return { locale, translated, total: totalKeys, percentage };
  });

  const totalTranslated = locales.reduce((sum, l) => sum + l.translated, 0);
  const totalPossible = totalKeys * targetLocales.length;
  const overallPercentage =
    totalPossible > 0 ? Math.round((totalTranslated / totalPossible) * 100) : 0;

  return { locales, totalKeys, overallPercentage };
}

export function generateBadgeUrl(percentage: number, localeCount: number): string {
  const color =
    percentage >= 98
      ? 'brightgreen'
      : percentage >= 90
      ? 'green'
      : percentage >= 75
      ? 'yellow'
      : percentage >= 50
      ? 'orange'
      : 'red';

  const label = encodeURIComponent('i18n');
  const message = encodeURIComponent(`${percentage}% | ${localeCount} locales`);
  return `https://img.shields.io/badge/${label}-${message}-${color}?style=flat-square`;
}

export function generateBadgeMarkdown(percentage: number, localeCount: number): string {
  const url = generateBadgeUrl(percentage, localeCount);
  return `![i18n](${url})`;
}

export function generateCoverageHtml(report: CoverageReport): string {
  const rows = report.locales
    .map((locale) => {
      const status =
        locale.percentage === 100
          ? 'Complete'
          : locale.percentage >= 80
          ? 'Good'
          : locale.percentage >= 50
          ? 'Needs attention'
          : 'Critical';
      return `<tr>
  <td>${locale.locale}</td>
  <td>${locale.translated}/${locale.total}</td>
  <td>${locale.percentage}%</td>
  <td>${status}</td>
</tr>`;
    })
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>koto i18n Coverage Report</title>
  <style>
    :root { color-scheme: light dark; }
    body { font-family: ui-sans-serif, system-ui, sans-serif; margin: 2rem auto; max-width: 820px; padding: 0 1rem; line-height: 1.5; }
    h1 { margin-bottom: 0.25rem; }
    .meta { margin: 0 0 1rem; color: #64748b; }
    .score { font-size: 2rem; font-weight: 700; margin: 0.5rem 0 1.5rem; }
    table { width: 100%; border-collapse: collapse; border: 1px solid #334155; }
    th, td { text-align: left; padding: 0.65rem 0.75rem; border-bottom: 1px solid #334155; }
    th { font-weight: 600; }
    tr:last-child td { border-bottom: 0; }
  </style>
</head>
<body>
  <h1>koto i18n Coverage Report</h1>
  <p class="meta">Generated by <code>koto badge</code></p>
  <p class="score">Overall coverage: ${report.overallPercentage}%</p>
  <table>
    <thead>
      <tr>
        <th>Locale</th>
        <th>Translated Keys</th>
        <th>Coverage</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>
</body>
</html>`;
}

export async function badgeCommand(cwd: string): Promise<void> {
  printCompact(VERSION);

  const config = await loadConfig(cwd);
  const lockfile = await readLockfile(cwd);
  const report = computeCoverage(lockfile, config.targetLocales);

  console.log(`  ${pc.bold('i18n Coverage Report')}\n`);

  for (const lc of report.locales) {
    const flag = getLanguageFlag(lc.locale);
    const pctStr = `${lc.percentage}%`;
    const color = lc.percentage === 100 ? pc.green(pctStr) : lc.percentage >= 80 ? pc.yellow(pctStr) : pc.red(pctStr);
    console.log(
      `  ${flag}  ${lc.locale.padEnd(8)} ${String(lc.translated).padStart(4)}/${lc.total} keys (${color})`,
    );
  }

  console.log(
    `\n  ${pc.bold('Overall:')} ${report.overallPercentage}% across ${report.locales.length} locales\n`,
  );

  const markdown = generateBadgeMarkdown(report.overallPercentage, report.locales.length);
  const jsonPath = join(cwd, 'koto-coverage.json');
  const htmlPath = join(cwd, 'koto-coverage.html');
  await writeFile(jsonPath, JSON.stringify(report, null, 2));
  await writeFile(htmlPath, generateCoverageHtml(report));

  console.log(`  ${pc.bold('Add to your README:')}\n`);
  console.log(`  ${pc.cyan(markdown)}\n`);
  console.log(`  ${pc.bold('Coverage artifacts:')}`);
  console.log(`  - ${pc.cyan('koto-coverage.json')}`);
  console.log(`  - ${pc.cyan('koto-coverage.html')}\n`);
}
