import { mkdtemp, writeFile, readFile, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { generateTypesFromConfig } from '../../src/core/typegen/index.js';

describe('type generation integration', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await mkdtemp(path.join(tmpdir(), 'koto-typegen-'));
    await mkdir(path.join(tmpDir, 'locales'), { recursive: true });
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true });
  });

  it('generates a .d.ts file with all keys as a union type', async () => {
    const source = {
      greeting: 'Hello',
      farewell: 'Goodbye',
      nested: {
        welcome: 'Welcome',
        deep: {
          value: 'Deep value',
        },
      },
    };
    await writeFile(
      path.join(tmpDir, 'locales', 'en.json'),
      JSON.stringify(source, null, 2),
    );

    const outputPath = 'koto.d.ts';
    const result = await generateTypesFromConfig(
      tmpDir,
      ['locales/[locale].json'],
      'en',
      outputPath,
    );

    expect(result.keyCount).toBe(4);

    const content = await readFile(path.resolve(tmpDir, outputPath), 'utf-8');

    // Should contain the auto-generated header
    expect(content).toContain('Generated by koto');
    expect(content).toContain('do not edit manually');

    // Should contain all keys in the union type
    expect(content).toContain("'greeting'");
    expect(content).toContain("'farewell'");
    expect(content).toContain("'nested.welcome'");
    expect(content).toContain("'nested.deep.value'");

    // Should have a TranslationKey type
    expect(content).toContain('export type TranslationKey =');
  });

  it('detects parameterized keys and generates TranslationParams', async () => {
    const source = {
      greeting: 'Hello, {{name}}!',
      items: 'You have {count} items',
      simple: 'No params here',
    };
    await writeFile(
      path.join(tmpDir, 'locales', 'en.json'),
      JSON.stringify(source, null, 2),
    );

    const outputPath = 'koto.d.ts';
    await generateTypesFromConfig(
      tmpDir,
      ['locales/[locale].json'],
      'en',
      outputPath,
    );

    const content = await readFile(path.resolve(tmpDir, outputPath), 'utf-8');

    // Should have TranslationParams type
    expect(content).toContain('export type TranslationParams =');

    // Parameterized keys should be in TranslationParams
    expect(content).toContain("'greeting'");
    expect(content).toContain('name: string | number');
    expect(content).toContain("'items'");
    expect(content).toContain('count: string | number');
  });

  it('generates a helper TranslateFunction type', async () => {
    const source = { hello: 'Hello' };
    await writeFile(
      path.join(tmpDir, 'locales', 'en.json'),
      JSON.stringify(source, null, 2),
    );

    const outputPath = 'koto.d.ts';
    await generateTypesFromConfig(
      tmpDir,
      ['locales/[locale].json'],
      'en',
      outputPath,
    );

    const content = await readFile(path.resolve(tmpDir, outputPath), 'utf-8');

    expect(content).toContain('export type TranslateFunction');
  });

  it('sorts keys alphabetically in the union type', async () => {
    const source = { zebra: 'Z', alpha: 'A', middle: 'M' };
    await writeFile(
      path.join(tmpDir, 'locales', 'en.json'),
      JSON.stringify(source, null, 2),
    );

    const outputPath = 'koto.d.ts';
    await generateTypesFromConfig(
      tmpDir,
      ['locales/[locale].json'],
      'en',
      outputPath,
    );

    const content = await readFile(path.resolve(tmpDir, outputPath), 'utf-8');

    const alphaIdx = content.indexOf("'alpha'");
    const middleIdx = content.indexOf("'middle'");
    const zebraIdx = content.indexOf("'zebra'");

    expect(alphaIdx).toBeLessThan(middleIdx);
    expect(middleIdx).toBeLessThan(zebraIdx);
  });

  it('handles multiple source files', async () => {
    await mkdir(path.join(tmpDir, 'common'), { recursive: true });

    const mainSource = { home: 'Home', about: 'About' };
    const commonSource = { ok: 'OK', cancel: 'Cancel' };

    await writeFile(
      path.join(tmpDir, 'locales', 'en.json'),
      JSON.stringify(mainSource, null, 2),
    );
    await writeFile(
      path.join(tmpDir, 'common', 'en.json'),
      JSON.stringify(commonSource, null, 2),
    );

    const outputPath = 'koto.d.ts';
    const result = await generateTypesFromConfig(
      tmpDir,
      ['locales/[locale].json', 'common/[locale].json'],
      'en',
      outputPath,
    );

    expect(result.keyCount).toBe(4);

    const content = await readFile(path.resolve(tmpDir, outputPath), 'utf-8');
    expect(content).toContain("'home'");
    expect(content).toContain("'about'");
    expect(content).toContain("'ok'");
    expect(content).toContain("'cancel'");
  });

  it('handles keys with multiple parameters', async () => {
    const source = {
      transfer: 'Transfer {{amount}} from {{sender}} to {{recipient}}',
    };
    await writeFile(
      path.join(tmpDir, 'locales', 'en.json'),
      JSON.stringify(source, null, 2),
    );

    const outputPath = 'koto.d.ts';
    await generateTypesFromConfig(
      tmpDir,
      ['locales/[locale].json'],
      'en',
      outputPath,
    );

    const content = await readFile(path.resolve(tmpDir, outputPath), 'utf-8');

    expect(content).toContain('amount: string | number');
    expect(content).toContain('sender: string | number');
    expect(content).toContain('recipient: string | number');
  });

  it('skips missing source files without errors', async () => {
    // Only create one of two expected files
    await writeFile(
      path.join(tmpDir, 'locales', 'en.json'),
      JSON.stringify({ hello: 'Hello' }, null, 2),
    );

    const outputPath = 'koto.d.ts';
    const result = await generateTypesFromConfig(
      tmpDir,
      ['locales/[locale].json', 'missing/[locale].json'],
      'en',
      outputPath,
    );

    // Should only count keys from existing files
    expect(result.keyCount).toBe(1);
  });
});
