import { readFile, writeFile } from '../../utils/fs.js';
import { getFormat } from '../../formats/registry.js';
import path from 'node:path';

export interface TypegenOptions {
  outputPath: string;
  sourceFiles: string[];
  sourceLocale: string;
}

export async function generateTypes(options: TypegenOptions): Promise<string> {
  const allKeys = new Map<string, string>();
  const paramKeys = new Map<string, string[]>();

  for (const filePath of options.sourceFiles) {
    const format = getFormat(filePath);
    const content = await readFile(filePath);
    const parsed = format.parse(content);

    for (const [key, value] of parsed.keys) {
      allKeys.set(key, value);

      const params = extractParams(value);
      if (params.length > 0) {
        paramKeys.set(key, params);
      }
    }
  }

  const output = buildTypeFile(allKeys, paramKeys);
  await writeFile(options.outputPath, output);
  return output;
}

function extractParams(value: string): string[] {
  const params: string[] = [];
  const seen = new Set<string>();

  const patterns = [
    /\{\{(\w+)\}\}/g,
    /\{(\w+)(?:,[^}]*)?\}/g,
  ];

  for (const pattern of patterns) {
    let match;
    while ((match = pattern.exec(value)) !== null) {
      const param = match[1];
      if (!seen.has(param)) {
        seen.add(param);
        params.push(param);
      }
    }
  }

  return params;
}

function escapeKey(key: string): string {
  return key.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function buildTypeFile(
  keys: Map<string, string>,
  paramKeys: Map<string, string[]>,
): string {
  const sortedKeys = [...keys.keys()].sort();

  const lines: string[] = [
    '// Generated by koto — do not edit manually',
    '// Run `npx koto types` to regenerate',
    '',
    'export type TranslationKey =',
  ];

  for (let i = 0; i < sortedKeys.length; i++) {
    const key = escapeKey(sortedKeys[i]);
    const separator = i < sortedKeys.length - 1 ? '' : ';';
    lines.push(`  | '${key}'${separator}`);
  }

  // Always emit TranslationParams (empty if no parameterized keys)
  lines.push('');
  lines.push('export type TranslationParams = {');

  if (paramKeys.size > 0) {
    const sortedParamKeys = [...paramKeys.keys()].sort();
    for (const key of sortedParamKeys) {
      const params = paramKeys.get(key)!;
      const paramType = params.map((p) => `${p}: string | number`).join('; ');
      lines.push(`  '${escapeKey(key)}': { ${paramType} };`);
    }
  }

  lines.push('};');

  lines.push('');
  lines.push('// Helper type for type-safe translation functions');
  lines.push('export type TranslateFunction = {');
  lines.push('  <K extends keyof TranslationParams>(key: K, params: TranslationParams[K]): string;');
  lines.push('  (key: Exclude<TranslationKey, keyof TranslationParams>): string;');
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

export async function generateTypesFromConfig(
  cwd: string,
  files: string[],
  sourceLocale: string,
  outputPath: string,
): Promise<{ keyCount: number; outputPath: string }> {
  const sourceFiles = files.map((pattern) =>
    path.resolve(cwd, pattern.replace('[locale]', sourceLocale)),
  );

  const existingFiles: string[] = [];
  for (const f of sourceFiles) {
    try {
      await readFile(f);
      existingFiles.push(f);
    } catch {
      // skip missing
    }
  }

  const output = await generateTypes({
    outputPath: path.resolve(cwd, outputPath),
    sourceFiles: existingFiles,
    sourceLocale,
  });

  const keyCount = (output.match(/\| '/g) || []).length;
  return { keyCount, outputPath };
}
