export const TYPE_FILE_HEADER = `// Generated by koto — do not edit manually
// Run \`npx koto types\` to regenerate
`;

export const DECLARATION_TEMPLATE = `
declare module 'koto/translations' {
  export type TranslationKey = __KEYS__;
  export type TranslationParams = __PARAMS__;
}
`;

export function formatKeyUnion(keys: string[]): string {
  if (keys.length === 0) return 'never';
  return keys.map((k) => `'${k}'`).join(' | ');
}

export function formatParamsType(params: Map<string, string[]>): string {
  if (params.size === 0) return '{}';

  const entries: string[] = [];
  for (const [key, paramNames] of params) {
    const fields = paramNames.map((p) => `${p}: string | number`).join('; ');
    entries.push(`'${key}': { ${fields} }`);
  }

  return `{\n  ${entries.join(';\n  ')};\n}`;
}
